OBJS = crypto.o 

AIKIDO = ../..

CPPFLAGS = -g -I$(AIKIDO)/include  -D_OS_MACOSX -D_CC_GCC -fPIC -Wno-deprecated-declarations

libaikidocrypto.so : $(OBJS) 
	$(CXX) -bundle -undefined suppress -flat_namespace -o libaikidocrypto.so $(OBJS) -lcrypto

clean:
	-rm -f *.o lib*.so
